"""initial tables

Revision ID: 5332f8e4c668
Revises: 
Create Date: 2026-02-18 17:01:31.699717
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5332f8e4c668'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('module_tag', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_module_tag'), 'log_entries', ['module_tag'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.Enum('NYC', 'CHI', 'MIA', 'AUS', name='cityenum', native_enum=False), nullable=False),
    sa.Column('prediction_date', sa.DateTime(), nullable=False),
    sa.Column('ensemble_mean_f', sa.Float(), nullable=False),
    sa.Column('ensemble_std_f', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('model_sources', sa.String(), nullable=False),
    sa.Column('brackets_json', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_city_date', 'predictions', ['city', 'prediction_date'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.Enum('NYC', 'CHI', 'MIA', 'AUS', name='cityenum', native_enum=False), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.Column('actual_high_f', sa.Float(), nullable=False),
    sa.Column('actual_low_f', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_settlement_city_date', 'settlements', ['city', 'settlement_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kalshi_key_id', sa.String(), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('trading_mode', sa.String(), nullable=True),
    sa.Column('max_trade_size_cents', sa.Integer(), nullable=True),
    sa.Column('daily_loss_limit_cents', sa.Integer(), nullable=True),
    sa.Column('max_daily_exposure_cents', sa.Integer(), nullable=True),
    sa.Column('min_ev_threshold', sa.Float(), nullable=True),
    sa.Column('cooldown_per_loss_minutes', sa.Integer(), nullable=True),
    sa.Column('consecutive_loss_limit', sa.Integer(), nullable=True),
    sa.Column('active_cities', sa.String(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_subscription', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_risk_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('trading_day', sa.DateTime(), nullable=False),
    sa.Column('total_loss_cents', sa.Integer(), nullable=True),
    sa.Column('total_exposure_cents', sa.Integer(), nullable=True),
    sa.Column('consecutive_losses', sa.Integer(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('trades_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_user_day', 'daily_risk_states', ['user_id', 'trading_day'], unique=True)
    op.create_table('pending_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('city', sa.Enum('NYC', 'CHI', 'MIA', 'AUS', name='cityenum', native_enum=False), nullable=False),
    sa.Column('bracket_label', sa.String(), nullable=False),
    sa.Column('market_ticker', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('market_probability', sa.Float(), nullable=False),
    sa.Column('ev', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'EXECUTED', name='pendingtradestatus', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('kalshi_order_id', sa.String(), nullable=True),
    sa.Column('city', sa.Enum('NYC', 'CHI', 'MIA', 'AUS', name='cityenum', native_enum=False), nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('market_ticker', sa.String(), nullable=False),
    sa.Column('bracket_label', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('market_probability', sa.Float(), nullable=False),
    sa.Column('ev_at_entry', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'WON', 'LOST', 'CANCELED', name='tradestatus', native_enum=False), nullable=True),
    sa.Column('settlement_temp_f', sa.Float(), nullable=True),
    sa.Column('settlement_source', sa.String(), nullable=True),
    sa.Column('pnl_cents', sa.Integer(), nullable=True),
    sa.Column('fees_cents', sa.Integer(), nullable=True),
    sa.Column('postmortem_narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_city_date', 'trades', ['city', 'trade_date'], unique=False)
    op.create_index('ix_trade_status', 'trades', ['status'], unique=False)
    op.create_index('ix_trade_user', 'trades', ['user_id'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('city', sa.Enum('NYC', 'CHI', 'MIA', 'AUS', name='cityenum', native_enum=False), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('forecast_high_f', sa.Float(), nullable=False),
    sa.Column('forecast_low_f', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_city_date', 'weather_forecasts', ['city', 'forecast_date'], unique=False)
    op.create_index('ix_forecast_source', 'weather_forecasts', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forecast_source', table_name='weather_forecasts')
    op.drop_index('ix_forecast_city_date', table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index('ix_trade_user', table_name='trades')
    op.drop_index('ix_trade_status', table_name='trades')
    op.drop_index('ix_trade_city_date', table_name='trades')
    op.drop_table('trades')
    op.drop_table('pending_trades')
    op.drop_index('ix_risk_user_day', table_name='daily_risk_states')
    op.drop_table('daily_risk_states')
    op.drop_table('users')
    op.drop_index('ix_settlement_city_date', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index('ix_prediction_city_date', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_module_tag'), table_name='log_entries')
    op.drop_table('log_entries')
    # ### end Alembic commands ###
